theme : jekyll-theme-prologue
remote_theme : chrisbobbe/jekyll-theme-prologue
title : 초보 개발자의 생각 끄적끄적 메모장
author : aixenhuh
email : aixenhuh@gmail.com
description : 여러 공부하면서 생각 적어놓은 공간입니다.
share : true
url : "https://aixenhuh.github.io"
baseurl : ""
owner : 
  name : "Song JY"
  email : "aixenhuh@gmail.com"
  description : "wow"
  github : aixenhuh
  
defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag
  - scope:
      path: 'events'
    values:
      layout: page
      sitemap: true

# Minima date format
minima:
  date_format: "%b %-d, %Y"
  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github: aixenhuh
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll
    
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
