remote_theme: jekyll/minima
title : aixenhuh's blog
share : true
url : "https://aixenhuh.github.io"
baseurl : ""
owner : 
  name : "Song JY"
  email : "aixenhuh@gmail.com"
  description : "wow"
  github : aixenhuh
  
defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag
  - scope:
      path: 'events'
    values:
      layout: page
      sitemap: true
